import { Temporal } from "@js-temporal/polyfill";
import z from "zod";
import { Mandatory } from "@/shared/types";

export const temporalGranularitySchema = z.enum([
  'years',
  'months',
  'weeks',
  'days',
]);

export type TemporalGranularity = z.infer<typeof temporalGranularitySchema>;
export const TEMPORAL_GRANULARITIES = temporalGranularitySchema.options;

/**
 * This type expresses the individual divisions between time periods.
 * For example, between today and yesterday:
 * - `window`: The time is today.
 * - `overlap`: The time is within the hours of yesterday AND WITHIN the
 * last 24 hours.
 * - `prior`: The time is within the hours of yesterday AND BEFORE the last 24
 * hours.
 * - `older`: Before yesterday.
 * - `future`: After now.
 * Can apply to time periods other than previous days, e.g. weeks, months or
 * years.
 */
export const temporalRelativeCategorySchema = z.union([
  z.literal('older').describe('Before the previous time period.'),
  z.literal('prior').describe(
    'In the previous time period before the last time period.'
  ),
  z.literal('overlap').describe(
    'Within the previous time period and the last time period.'
  ),
  z.literal('window').describe('The current time period.'),
  z.literal('future').describe('After now.'),
]);

export type TemporalRelativeCategory = z.infer<typeof temporalRelativeCategorySchema>;

export const temporalGranularitySummaryPopulationSchema = z.union([
  z.literal('full').describe('All frequency values are non-zero.'),
  z.literal('last').describe('All overlap and window values are non-zero.'),
  z.literal('insufficient').describe(
    'One or more overlap or window values are zero.'
  ),
]);

export type TemporalGranularitySummaryPopulation = z.infer<
  typeof temporalGranularitySummaryPopulationSchema
>;

export const temporalPeriodSchema = z.object({
  category: temporalRelativeCategorySchema,
  /**
   * E.g. beginning of the month/week/day
   * Calculating the other properties means we already have this data.
   */
  start: z.instanceof(Temporal.ZonedDateTime),
  /**
   * The end date time would be the last second of the period in question, but
   * we haven't already calculated it and there is no precendent for its utility
   * yet, so it hasn't been made a requirement for the type.
   * E.g. end of the month/week/day
   */
  // end: Temporal.ZonedDateTime;
  /**
   * The string representation of the start date as generated by
   * `getFrequencyKey` at this time.
   */
  key: z.string(),
  /**
   * This is the numeric value relevant to this period, whatever that value may
   * express. One example would be frequencies of occurrence in that period,
   * such as git commits for the week or diary entries for the day.
   */
  value: z.number().default(0),
});

export type TemporalPeriod = z.infer<typeof temporalPeriodSchema>;

export const temporalGranularityConfigItemSchemaFactory = <
  BreakdownKey extends keyof Temporal.ZonedDateTime & string,
  DurationKey extends keyof Temporal.Duration & string,
  SizeKey extends keyof Temporal.ZonedDateTime & string,
>(
  breakdownKey: BreakdownKey,
  durationKey: DurationKey,
  sizeKey: SizeKey
) => z.object({
  breakdownKey: z.literal<BreakdownKey>(breakdownKey).describe(
    'The date increment property which the period breaks down into.'
  ).default(breakdownKey),
  current: z.instanceof(Temporal.ZonedDateTime),
  durationKey: z.literal<DurationKey>(durationKey).default(durationKey),
  from: z.instanceof(Temporal.ZonedDateTime),
  increment: z.function({
    input: z.array(z.instanceof(Temporal.ZonedDateTime)),
    output: z.instanceof(Temporal.ZonedDateTime),
  }),
  quantise: z.function({
    input: z.array(z.instanceof(Temporal.ZonedDateTime)),
    output: z.instanceof(Temporal.ZonedDateTime),
  }),
  sizeKey: z.literal<SizeKey>(sizeKey).default(sizeKey),
});

export type TemporalGranularityConfigItem<
  BreakdownKey extends keyof Temporal.ZonedDateTime & string = keyof Temporal.ZonedDateTime & string,
  DurationKey extends keyof Temporal.DurationLike & string = keyof Temporal.DurationLike & string,
  SizeKey extends keyof Temporal.ZonedDateTime & string = keyof Temporal.ZonedDateTime & string,
> = z.infer<ReturnType<typeof temporalGranularityConfigItemSchemaFactory<
  BreakdownKey, DurationKey, SizeKey
>>>;

export const temporalGranularityConfigSchema = z.object({
  years: temporalGranularityConfigItemSchemaFactory('month', 'months', 'monthsInYear'),
  months: temporalGranularityConfigItemSchemaFactory('day', 'days', 'daysInMonth'),
  weeks: temporalGranularityConfigItemSchemaFactory('dayOfWeek', 'days', 'daysInWeek'),
  days: temporalGranularityConfigItemSchemaFactory('hour', 'hours', 'hoursInDay'),
});

export type TemporalGranularityConfig = z.infer<typeof temporalGranularityConfigSchema>;

type TemporalGranularityParseParams = {
  [Granularity in keyof TemporalGranularityConfig]: Mandatory<
    TemporalGranularityConfig[Granularity],
    'current' | 'from' | 'increment' | 'quantise'
  >;
};
export const temporalGranularityParse = (
  config: TemporalGranularityParseParams
) => temporalGranularityConfigSchema.parse(config);

export const temporalGranularityFrequenciesSchema = z.object({
  current: z.instanceof(Temporal.ZonedDateTime).describe(
    'The date at the beginning of the current granularity period, e.g. 1st of this month or year.'
  ),
  from: z.instanceof(Temporal.ZonedDateTime).describe(
    'The date at the beginning of the previous granularity period, e.g. 1st of last month or year.'
  ),
  granularity: temporalGranularitySchema,
  breakdownKey: z.string(), // Technically should be a keyof Temporal.ZonedDateTime.
  priorThreshold: z.instanceof(Temporal.ZonedDateTime),
  /**
   * @deprecated Try to avoid using this as it's not consistent on a monthly
   * level. We can calculate numbers of 0-values from frequencies.
   */
  size: z.number(), // Because we already have it.
  // to: Temporal.ZonedDateTime; // If we need it.
  quantise: z.function({
    input: z.array(z.instanceof(Temporal.ZonedDateTime)),
    output: z.instanceof(Temporal.ZonedDateTime),
  }),
  frequencies: z.record(z.string(), temporalPeriodSchema),
  summary: z.object({
    populated: temporalGranularitySummaryPopulationSchema.default('insufficient'),
  }),
});

export type TemporalGranularityFrequencies<
  Granularity extends TemporalGranularity = 'days'
> = z.infer<typeof temporalGranularityFrequenciesSchema>;

export const temporalFrequenciesSchema = z.record(
  temporalGranularitySchema,
  temporalGranularityFrequenciesSchema
);

export type TemporalFrequencies = z.infer<typeof temporalFrequenciesSchema>;
