export const CHANNEL_SUBSCRIBE_TO_DOCKER_CHECKLIST = 'subscribeToDockerChecklist';
export const CHANNEL_SUBSCRIBE_TO_RITUAL_TELEMETRY = 'subscribeToRitualTelemetry';

export type ChannelSubscribeToDockerChecklist = typeof CHANNEL_SUBSCRIBE_TO_DOCKER_CHECKLIST;
export type ChannelSubscribeToRitualTelemetry = typeof CHANNEL_SUBSCRIBE_TO_RITUAL_TELEMETRY;
