import { app, BrowserWindow, ipcMain } from 'electron';
import path from 'path';
import { EVENT_SUBSCRIPTION_WINDOW_EVENT_FOCUSED } from './ipc';
// import { getDatabase } from './main/database';
// import { getCommands } from './main/docker/commands';
// import { setupDockerChecklistHandler } from './main/docker/ipc';
import { manageEnvironment } from './main/environment';
import { setupRitualTelemetryHandler } from './main/features/ai/ipc';
import { diaryIpc } from './main/features/diary/ipc';
import { emailHandlers } from './main/features/email';
import { tasksIpc, triageTasks } from './main/features/tasks';
import { setupHandlers } from './main/ipc/setup-handlers';
import { registerVessel } from './main/shared/vessel';
import { initializeFirebase } from './main/libs/firebase';
import { crmIpc } from './main/features/crm';
import { jobSearchIpc } from './main/features/job-search';
import { projectsIpc } from '@main/features/projects/ipc';
import { log as appLog } from '@main/shared/logging';
import { createIPCHandler } from 'trpc-electron/main';
import { router } from './trpc/router';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).

const log = (...args: string[]) => {
  args.forEach((arg) => appLog(`src/main.ts: ${arg}`, 'info'));
}

log('Application initialised.');

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 1000,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: true,
    },
  });

  // and load the index.html of the app.
  // mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`));
  }

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  mainWindow.maximize();

  mainWindow.on('focus', () => {
    mainWindow.webContents.send(EVENT_SUBSCRIPTION_WINDOW_EVENT_FOCUSED);
  });

  setupRitualTelemetryHandler(ipcMain);

  registerVessel(mainWindow);

  createIPCHandler({ router, windows: [mainWindow] });
};

const initialise = () => {
  initializeFirebase();

  log('Setting up IPC handlers...');
  // TODO: We want to avoid needing all these items pulled into the application.
  // To keep main and renderer separate, this kind of "dependency injection" is
  // necessary.
  // IN THEORY it doesn't stop us from outputting the suitable type.
  // IF WE PUT the handler-compatible functions in here, which we can generate
  // with utilities of various kinds.
  setupHandlers({
    crm: crmIpc,
    // database,
    diary: diaryIpc(),
    // docker: getCommands(),
    environment: manageEnvironment(),
    jobSearch: jobSearchIpc,
    projects: projectsIpc,
    tasks: tasksIpc(),
    triage: {
      ...emailHandlers,
      triageTasks
    }
  });

  appLog('IPC handlers set up.', 'success');
};

initialise();

// Setting up app.on events doesn't work well asynchronously, but ideally we need the database pool set up once.
// log('Setting up database...')
// getDatabase().then((database) => {
//   appLog('Database is ready.', 'success');
// });


// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  appLog('App is ready.', 'success');
  log('Creating window...');
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  log('All windows closed. Quitting app.');
  ipcMain.removeAllListeners();
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  log('App activated.');
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
